spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.75.73.237:3306/isqzy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: qizy
    password: qizhiyong
  data:
    mongodb:
      uri: mongodb://qizy:qizhiyong@47.75.73.237:17017/isqzy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
