server:
  port: 14001
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://:3306/isqzy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
